create table public.agents (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  title jsonb null,
  description jsonb null,
  input jsonb null,
  output jsonb null,
  credits_per_run integer null default 0,
  workflow_id text null,
  stars bigint null default '0'::bigint,
  image_url text null,
  max_execution_time_secs integer null default 0,
  agent_endpoint text null,
  icon_svg text null,
  authentication text null default 'none'::text,
  agent_endpoint_method text null default 'POST'::text,
  configuration jsonb null,
  input_example jsonb null,
  output_example jsonb null,
  task_prompt text null,
  type public.agent_composition_type null default 'atom'::public.agent_composition_type,
  output_type public.agent_output_type null default 'content-creation'::public.agent_output_type,
  wrapped_url text null,
  workflow_webhook_url text null,
  content_extraction_file_extensions text null,
  constraint agents_pkey primary key (id)
) TABLESPACE pg_default;