create table public.user_roles (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  role public.app_role not null,
  constraint user_roles_pkey primary key (id),
  constraint user_roles_user_id_role_key unique (user_id, role),
  constraint user_roles_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.role_permissions (
  id bigint generated by default as identity not null,
  role public.app_role not null,
  permission public.app_permission not null,
  constraint role_permissions_pkey primary key (id),
  constraint role_permissions_role_permission_key unique (role, permission)
) TABLESPACE pg_default;

insert into public.role_permissions (role, permission)
values
  ('developer', 'dashboards.view'),
  ('developer', 'dashboards.edit'),
  ('customer', 'dashboards.view');